name: 'Upload last-master versions to GH Packages'

on:
  push:
    branches:
      - publish-nuget-test   # for a test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
          
      - name: 'Clone AngouriMath'   # will be via github's checkout actions
        run: git clone https://github.com/asc-community/AngouriMath .
        
      - name: 'Pack AngouriMath'
        run: |
          cd Sources
          dotnet nuget add source --username WhiteBlackGoose --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
          
          # versioning
          commithash=$(git rev-parse --short HEAD)
          echo "commit hash is $commithash"
          name=0.0.0-master$commithash
          echo "name is $name"
          
          # AngouriMath
          cd AngouriMath
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push AngouriMath.$name.nupkg --api-key ${{ secrets.PACKAGES }} --source "github"
          cd ..
          
          # AngouriMath.FSharp
          cd Wrappers/AngouriMath.FSharp
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push AngouriMath.FSharp.$name.nupkg --api-key ${{ secrets.PACKAGES }} --source "github"
          cd ../..
          
          # AngouriMath.Interactive
          cd Wrappers/AngouriMath.Interactive
          dotnet restore
          dotnet build -c release
          dotnet pack -c release -p:PackageVersion=$name
          cd bin/release
          dotnet nuget push AngouriMath.Interactive.$name.nupkg --api-key ${{ secrets.PACKAGES }} --source "github"
          cd ../..
