name: 'Upload last-master versions to GH Packages'

on:
  push:
    branches:
      - publish-nuget-test   # for a test

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.202'
          
      - name: 'Clone AngouriMath'   # will be via github's checkout actions
        run: git clone https://github.com/asc-community/AngouriMath .
        
      - name: 'Pack AngouriMath'
        run: |
          cd Sources/AngouriMath
          dotnet restore
          dotnet build -c release
          dotnet pack -c release --version-suffix $(git rev-parse --verify HEAD)
          dotnet nuget add source --username WhiteBlackGoose --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"
          cd bin/Release
          dotnet nuget push AngouriMath.1.3.0-preview.4.nupkg --api-key ${{ secrets.PACKAGES }} --source "github"
